version: 2
updates:
- package-ecosystem: cargo
  directory: "/wasm/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/js/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
