name: Deploy
on:
  push:
    branches:
      - prod
env:
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: prod
      # Rust
      - run: cargo install wasm-pack
        working-directory: ./wasm
      - run: wasm-pack build
        working-directory: ./wasm
      # JS
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: npm install
        run: npm install
        working-directory: ./js
      - name: npm run build
        run: npm run build
        working-directory: ./js
      # Deploy
      - name: AWS CLI setup
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: kevinpthornecom-github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}
      - name: Test AWS CLI authn
        run: aws sts get-caller-identity
      - name: Upload to S3
        run: aws s3 sync $SOURCE_DIR s3://$AWS_S3_BUCKET/ --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          SOURCE_DIR: ${{ vars.BUILD_DIR || 'dist' }}
        working-directory: ./js
      - name: Clear CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id $DISTRO_ID --paths "/*"
        env:
          DISTRO_ID: ${{ secrets.CLOUDFRONT_DISTRO_ID }}
